### ISSUE TITLE
  能更新下yolov8-pose 推理支持吗？

### ISSUE THREAD

**Issue by yswang0927** [15911075183ma/java-onnx-yolov8#1]
您好，请问什么时候能出个 yolov8-pose 推理支持呢？

**Comment by mazp99** [comment]
应该是类似的逻辑您可以尝试自己转换一下

**Comment by yswang0927** [comment]
> 应该是类似的逻辑您可以尝试自己转换一下

@15911075183ma  我参考了您的代码，尝试去解析 pose 的输出，始终没有成功， 我现在遇到一个难题，yolov8-pose 输出的结果是 tenser-float32 [1, 56, 8400] ，然后我把矩阵进行了行列转换并去除batch层，得到 [8400, 56] 矩阵，从官网说，56个值，分别是：[0, 3] - 是bbox的4个坐标， [4] - 是分数，[5,51] - 是17个关键点*3，但是从数据看 [4] - 分数值应该是 < 1 的，但是实际结果不是。

**Comment by mazp99** [comment]
> > 应该是类似的逻辑您可以尝试自己转换一下
> 
> @15911075183ma 我参考了你的代码，尝试去解析pose的输出，始终没有成功，我现在遇到一个难题，yolov8-pose输出的结果是tenser-float32 [1, 56, 8400] ，然后我把Matrix进行了行列转换并增加batch层，得到 [8400, 56] 矩阵，从官网说，56个值，分别是：[0, 3] - 是bbox的4个坐标， [4] - 是分数，[5,51] - 是17个关键点*3，但是从数据看[4] - 分数值应该是 < 1 的，但实际结果不是。

这个应该是值需要转换一下，我周末看一下怎么处理一下

**Comment by mazp99** [comment]
@yswang0927 我更新了一下V11的pose，虽然我没有尝试v8版本的，但我认为它是一样的处理方式，您可以导出v8试一下，或者直接使用v11

**Comment by yswang0927** [comment]
> @yswang0927 我更新了一下V11的pose，虽然我没有尝试v8版本的，但我认为它是一样的处理方式，您可以导出v8试一下，或者直接使用v11

好的，非常感谢您，O(∩_∩)O
